import { Adventure, User } from './supabase';

// Sample users
export const sampleUsers: User[] = [
  {
    id: '1',
    email: 'alex@example.com',
    username: 'alexadventurer',
    full_name: 'Alex Thompson',
    role: 'adventurer',
    completed_adventures_count: 3,
    total_encouragements_given: 45,
    total_encouragements_received: 78,
    joined_at: '2024-01-15T00:00:00Z',
    bio: 'Hot air balloon pilot and adventure seeker',
    location: 'Colorado, USA'
  },
  {
    id: '2',
    email: 'sarah@example.com',
    username: 'sarahexplorer',
    full_name: 'Sarah Chen',
    role: 'avid_adventurer',
    completed_adventures_count: 12,
    total_encouragements_given: 156,
    total_encouragements_received: 234,
    joined_at: '2023-08-20T00:00:00Z',
    bio: 'Paragliding instructor and world traveler',
    location: 'Chamonix, France'
  },
  {
    id: '3',
    email: 'mike@example.com',
    username: 'miketrails',
    full_name: 'Mike Rodriguez',
    role: 'authenticated',
    completed_adventures_count: 0,
    total_encouragements_given: 12,
    total_encouragements_received: 5,
    joined_at: '2024-12-01T00:00:00Z',
    bio: 'New to adventure, big dreams',
    location: 'Austin, Texas'
  }
];

// Sample adventures
export const sampleAdventures: Adventure[] = [
  {
    id: '1',
    title: 'Hitchhike Across the American Train System',
    slug: 'hitchhike-american-train-system',
    description: 'An epic journey combining hitchhiking and train hopping to cross the entire United States without flying or driving. Document the stories of people met along the way and the forgotten corners of America.',
    type: 'idea',
    status: 'published',
    is_journey: true,
    start_location_name: 'New York City, NY',
    start_latitude: 40.7128,
    start_longitude: -74.0060,
    end_location_name: 'San Francisco, CA',
    end_latitude: 37.7749,
    end_longitude: -122.4194,
    difficulty_score: 8,
    adventure_score: 9,
    success_metrics: [
      'Cross all 4 time zones',
      'Document 50 unique human stories',
      'Spend less than $500 total',
      'Visit at least 3 abandoned train stations'
    ],
    creator_id: '1',
    creator: sampleUsers[0],
    encouragements_count: 127,
    comments_count: 34,
    contributions_total: 2450,
    saved_count: 89,
    tags: ['hitchhiking', 'trains', 'cross-country', 'documentary', 'budget'],
    created_at: '2024-11-15T00:00:00Z',
    updated_at: '2024-12-01T00:00:00Z'
  },
  {
    id: '2',
    title: 'Solo Balloon Flight Over the Alps',
    slug: 'solo-balloon-flight-alps',
    description: 'A solo hot air balloon journey across the Swiss Alps, launching from Interlaken and landing wherever the winds take you. Capture the sunrise over the Matterhorn and document the experience.',
    type: 'completed',
    status: 'published',
    is_journey: false,
    start_location_name: 'Interlaken, Switzerland',
    start_latitude: 46.6863,
    start_longitude: 7.8632,
    difficulty_score: 9,
    adventure_score: 10,
    success_metrics: [
      'Complete solo flight over 4 hours',
      'Photograph sunrise over Matterhorn',
      'Land safely in designated zone',
      'Document weather conditions throughout'
    ],
    creator_id: '2',
    creator: sampleUsers[1],
    encouragements_count: 203,
    comments_count: 67,
    contributions_total: 0,
    saved_count: 156,
    tags: ['ballooning', 'alps', 'solo', 'photography', 'switzerland'],
    completion_date: '2024-10-12T00:00:00Z',
    completion_evidence_url: 'https://example.com/alps-balloon-video',
    created_at: '2024-09-20T00:00:00Z',
    updated_at: '2024-10-15T00:00:00Z'
  },
  {
    id: '3',
    title: 'Midnight Paragliding in the Northern Lights',
    slug: 'midnight-paragliding-northern-lights',
    description: 'Paraglide under the aurora borealis in northern Norway during the polar night. Time the flight to coincide with peak aurora activity and capture the experience on film.',
    type: 'idea',
    status: 'published',
    is_journey: false,
    start_location_name: 'Tromsø, Norway',
    start_latitude: 69.6492,
    start_longitude: 18.9553,
    difficulty_score: 10,
    adventure_score: 10,
    success_metrics: [
      'Fly during active aurora (KP index 4+)',
      'Maintain flight for minimum 30 minutes',
      'Capture 4K video of the experience',
      'Land safely in designated area',
      'Document temperature and wind conditions'
    ],
    creator_id: '2',
    creator: sampleUsers[1],
    encouragements_count: 89,
    comments_count: 23,
    contributions_total: 1200,
    saved_count: 67,
    tags: ['paragliding', 'northern-lights', 'norway', 'extreme', 'night-flying'],
    created_at: '2024-12-01T00:00:00Z',
    updated_at: '2024-12-01T00:00:00Z'
  },
  {
    id: '4',
    title: 'Sail Solo Around Cape Horn',
    slug: 'sail-solo-cape-horn',
    description: 'Single-handed sailing around Cape Horn, one of the most dangerous passages in the world. Document the journey and the mental challenges of solo ocean sailing.',
    type: 'idea',
    status: 'published',
    is_journey: true,
    start_location_name: 'Ushuaia, Argentina',
    start_latitude: -54.8019,
    start_longitude: -68.3030,
    end_location_name: 'Puerto Williams, Chile',
    end_latitude: -54.9333,
    end_longitude: -67.6167,
    difficulty_score: 10,
    adventure_score: 9,
    success_metrics: [
      'Complete passage in under 72 hours',
      'Maintain detailed weather log',
      'Document psychological state daily',
      'Survive winds over 50 knots',
      'No outside assistance'
    ],
    creator_id: '3',
    creator: sampleUsers[2],
    encouragements_count: 45,
    comments_count: 12,
    contributions_total: 800,
    saved_count: 34,
    tags: ['sailing', 'cape-horn', 'solo', 'extreme-weather', 'ocean'],
    created_at: '2024-11-28T00:00:00Z',
    updated_at: '2024-11-30T00:00:00Z'
  },
  {
    id: '5',
    title: 'Desert Survival Challenge: 7 Days, 7 Items',
    slug: 'desert-survival-7-days-7-items',
    description: 'Survive 7 days in the Mojave Desert with only 7 chosen items. No food, no water provided - everything must be found, made, or rationed from the initial supplies.',
    type: 'idea',
    status: 'published',
    is_journey: false,
    start_location_name: 'Mojave Desert, California',
    start_latitude: 35.0178,
    start_longitude: -115.4734,
    difficulty_score: 9,
    adventure_score: 8,
    success_metrics: [
      'Survive 7 full days',
      'Find or create water source',
      'Build functional shelter',
      'Document daily survival activities',
      'Maintain detailed item usage log',
      'Signal for pickup on day 7'
    ],
    creator_id: '1',
    creator: sampleUsers[0],
    encouragements_count: 78,
    comments_count: 28,
    contributions_total: 1500,
    saved_count: 45,
    tags: ['survival', 'desert', 'minimalism', 'endurance', 'self-reliance'],
    created_at: '2024-11-20T00:00:00Z',
    updated_at: '2024-11-25T00:00:00Z'
  }
]; 